version: '2.3'
services:
 sirf:
  image: ccpsynerbi/sirf:service
  restart: unless-stopped
  environment:
   GADGETRON_RELAY_HOST: 0.0.0.0
  build:
   target: service
   cache_from:
    - ccpsynerbi/sirf:core
    - ccpsynerbi/sirf:latest
    - ccpsynerbi/sirf:service
  ports:
   - "9002:9002"  # gadgetron
   - "9999:8888"  # jupyter
   # for scaling, use this instead for random port assignment
   # (https://github.com/docker/compose/issues/2260):
   #- "9000-9099:9002"
   #- "8800-8899:8888"
