name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_dependencies
      run: 
          cd docker;
          sudo bash raw-ubuntu.sh;
          sudo bash build_essential-ubuntu.sh;
          sudo bash build_python-ubuntu.sh;
          sudo bash build_gadgetron-ubuntu.sh;
          sudo bash build_system-ubuntu.sh;
          bash user_python-ubuntu.sh ~/devel/install python3 ;        
    - name: configure
      shell: bash
      run: 
          set -ex;
          export superbuild=`pwd`;
          export BUILD_FLAGS="-DCMAKE_BUILD_TYPE=Release -DBUILD_STIR_WITH_OPENMP=ON -DUSE_SYSTEM_ACE=ON -DUSE_SYSTEM_Armadillo=ON -DUSE_SYSTEM_Boost=ON -DUSE_SYSTEM_FFTW3=ON -DUSE_SYSTEM_HDF5=ON -DUSE_ITK=ON -DBUILD_siemens_to_ismrmrd=ON -DUSE_SYSTEM_SWIG=ON -DCMAKE_INSTALL_PREFIX=~/install";
          export EXTRA_BUILD_FLAGS="";
          mkdir -p build/;
          cd build;
          echo "install dir/buildVM is" ;
          pwd;
          echo "Is the SuperBuild in ${superbuild}?";
          ls ${superbuild};
          echo "let us call cmake from ${INSTALL_DIR}/buildVM";
          export CC="gcc-7";
          export CXX="g++-7";
          cmake -S ${GITHUB_WORKSPACE} ${BUILD_FLAGS} ${EXTRA_BUILD_FLAGS} ;
    - name: make
      run: 
          export INSTALL_DIR=~/install;
          cd ${GITHUB_WORKSPACE}/build;
          cmake --build . ;
    - name: tests
      run: 
          export INSTALL_DIR=devel;
          source ${INSTALL_DIR}/install/bin/env_sirf.sh ;
          gadgetron >& gadgetron.log& ;
          cd ${INSTALL_DIR}/buildVM ;
          ctest --output-on-failure; test_fail=$? ;
